apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: finops
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      # Scrape the fintech backend's /metrics endpoint
      - job_name: 'fintech-backend'
        static_configs:
          - targets: ['fintech-backend-stable:5000']
        metrics_path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: finops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.52.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-vol
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-vol
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: finops
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
