apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: finops
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.finops:9090
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: finops
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'AuraFinance Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: finops
data:
  fintech-dashboard.json: |
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "title": "HTTP Request Rate",
          "type": "timeseries",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "Prometheus"
              },
              "editorMode": "code",
              "expr": "sum(rate(http_requests_total[1m])) by (status_code)",
              "legendFormat": "{{status_code}}",
              "range": true,
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "custom": {
                "drawStyle": "line",
                "lineInterpolation": "smooth"
              },
              "unit": "rps"
            }
          }
        },
        {
          "collapsed": false,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "title": "HTTP Success Rate (%)",
          "type": "timeseries",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "Prometheus"
              },
              "editorMode": "code",
              "expr": "(sum(rate(http_requests_total{status_code!~\"5..\"}[1m])) or vector(0)) / (sum(rate(http_requests_total[1m])) or vector(0)) * 100 or vector(100)",
              "legendFormat": "Success Rate %",
              "range": true,
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "custom": {
                "drawStyle": "line",
                "lineInterpolation": "smooth"
              },
              "unit": "percent",
              "max": 100,
              "min": 0
            }
          }
        },
        {
          "collapsed": false,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 3,
          "title": "Business Transaction Frequency (Inflow vs Outflow)",
          "type": "timeseries",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "Prometheus"
              },
              "editorMode": "code",
              "expr": "sum(rate(fintech_transactions_total[1m])) by (type)",
              "legendFormat": "{{type}}",
              "range": true,
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "custom": {
                "drawStyle": "line",
                "lineInterpolation": "smooth"
              },
              "unit": "ops"
            }
          }
        },
        {
          "collapsed": false,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 4,
          "title": "Active SSE connections",
          "type": "stat",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "Prometheus"
              },
              "editorMode": "code",
              "expr": "active_sse_connections",
              "legendFormat": "Active Clients",
              "range": true,
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "none"
            }
          }
        }
      ],
      "refresh": "5s",
      "schemaVersion": 39,
      "tags": [],
      "style": "dark",
      "timezone": "",
      "title": "AuraFinance Telemetry",
      "weekStart": ""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: finops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.0.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          volumeMounts:
            - name: grafana-datasources-vol
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-providers-vol
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-vol
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-datasources-vol
          configMap:
            name: grafana-datasources
        - name: grafana-providers-vol
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboards-vol
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: finops
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
